//Styles Start
import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import "normalize.css/normalize.css";
//Styles End
import Script from "next/script";
import "../styles/button.module.css";
//Components Start
import Head from "next/head";
import Navbar from "../components/Navbar";
//Components End

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Ramhard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Component {...pageProps} />

      <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"></Script>
    </>
  );
}

export default MyApp;
